version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    container_name: keycloak_mcp
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_WEB_ORIGINS=http://localhost:6274
      - KC_HTTP_ENABLED=true
      - KC_CORS=true
      - KC_CORS_ALLOWED_ORIGINS="*"  # ←全オリジン許可（開発中のみ）
    volumes:
      - keycloak_data:/opt/keycloak/data
    network_mode: "host"
volumes:
  keycloak_data: